# Generated by Django 4.0.8 on 2023-02-11 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('arrival_time', models.DateTimeField()),
                ('total_passanger', models.SmallIntegerField()),
                ('vehicle_type', models.CharField(choices=[('b', 'BMW'), ('f', 'Ford'), ('k', 'Kia'), ('m', 'Maserati'), ('n', 'Nissan')], max_length=1)),
                ('sharable', models.BooleanField()),
                ('special_requests', models.CharField(max_length=100)),
                ('completed_time', models.DateTimeField()),
                ('user', models.ManyToManyField(to='catalog.user')),
            ],
            options={
                'ordering': ['completed_time'],
            },
        ),
    ]
