# Generated by Django 4.0.8 on 2023-02-12 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_driver_order_is_completed_order_plate_numer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='completed_time',
            field=models.DateTimeField(),
        ),
    ]
