# Generated by Django 4.0.8 on 2023-02-12 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_order_completed_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='plate_numer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
